---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieseldong.
--- DateTime: 2021/6/23 0023 10:56
---

---@class CommonAPI
local CommonAPI = {}

function CommonAPI.GetModRoot()

end

function CommonAPI.GetAllModName()

end