---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieseldong.
--- DateTime: 2021/6/23 0023 14:37
---
require("define")

local ShowMsg = {}

---@param warnMsgs CheckSingleConfigResult[]
function ShowMsg.Show(warnMsgs)

    --https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=c2e98850-639c-4887-a0c4-6628b6b9d728
    WeCom.SetKey("c2e98850-639c-4887-a0c4-6628b6b9d728")

    local count = 0
    for configName, configMsg in pairs(warnMsgs) do

        if configMsg:HasAnyMsg() then
            local msg = configMsg:ToString()
            local content = "#【地图资源检测工具】"..configName.."\n"
            content = content..msg
            print(content)
            WeCom.SendMarkDown(content)
        end
        count = count + 1
    end

    if count == 0 then
        local content = "【地图资源检测工具】检查完成 未发现任何问题~"
        print(content)
        WeCom.SendMarkDown(content)
    end
end

return ShowMsg