---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieseldong.
--- DateTime: 2021/6/23 0023 17:50
---

---@field Desc string
---@field Args table
---@field Func fun()
---@class CheckFunction

---@field CheckFuncs CheckFunction[]
---@field Desc string
---@field Regex string[]
---@class MapRule

---@field Desc string
---@field Rules MapRule[]
---@field MapFolders string[]
---@class MapConfig
