---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieseldong.
--- DateTime: 2021/6/24 0024 11:58
---

require("define")

local Main = {}

function Main:main()

    ---@type LuaArray
    local modNames = LuaCommon.GetModNames()
    print("mode number "..modNames:Num())

    for i=0,modNames:Num()-1 do
        print("mod name : "..modNames:Get(i))
    end


end

return Main